spring:
  jpa:
    show-sql: true
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    #    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/bmoneytracker
    url: jdbc:h2:file:~/embedded-db:sa:org.h2.Driver
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    username: postgres
#    password: postgres
#    initialization-mode: never
jwt:
  secret: bmoneytracker
